services:
  - type: web
    name: spotshare-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: spotshare-postgres
          property: connectionString
      - key: NOMINATIM_USER_AGENT
        value: "SpotShare/1.0 (+https://render.com)"
      - key: CLIENT_ORIGIN
        value: "https://spotshare-psi.vercel.app"
      - key: PUBLIC_APP_URL
        value: "https://spotshare-psi.vercel.app"

databases:
  - name: spotshare-postgres
    plan: free
    databaseName: spotshare
    user: spotshare
